#!/usr/bin/bash

while getopts "m" opt; do
  case $opt in
    m)
      move=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done

workspace=$(swaymsg -t get_workspaces | jq -r -c '.[] | [.name,.focused]' | grep ",false]" | cut -d "\"" -f 2 | bemenu -p 'move to workspace' --fn "Terminus 8")

if [[ "$move" == "true" ]]
then
  swaymsg move container to workspace "$workspace"
else
  swaymsg workspace "$workspace"
fi
